# -----------------------------------------------------------------------------
# Script  : .github/actions/k8s-platform/config-upload/action.yaml
# Purpose : Generates a kubeconfig for the application service account and uploads it to S3
# -----------------------------------------------------------------------------
name: "Generate and Upload App Config"
description: "Generates a kubeconfig for the application service account and uploads it to S3"
inputs:
  sa_name:
    description: "Service Account Name"
    required: true
  namespace:
    description: "Namespace"
    required: true
  cluster_env:
    description: "Cluster Environment (dev/qa/prod)"
    required: true
  kube_config_bucket:
    description: "S3 Bucket for Kubeconfig"
    required: true

runs:
  using: "composite"
  steps:
    # ---------------------------------------------
    # Step 1: Install Dependencies
    # ---------------------------------------------
    - name: Install Python Dependencies
      shell: bash
      run: pip install pyyaml

    # ---------------------------------------------
    # Step 2: Generate Kubeconfig
    # ---------------------------------------------
    - name: Generate Kubeconfig
      shell: bash
      run: |
        python ${{ github.action_path }}/_get_kube_config.py \
          --service-account-name ${{ inputs.sa_name }} \
          --namespace ${{ inputs.namespace }} \
          --token-ttl 8760h

    # ---------------------------------------------
    # Step 3: Upload to S3
    # ---------------------------------------------
    - name: Upload to S3
      shell: bash
      run: |
        echo "Uploading config to s3://${{ inputs.kube_config_bucket }}/config"
        aws s3 cp ${{ inputs.sa_name }}-config.yaml s3://${{ inputs.kube_config_bucket }}/config
