# -----------------------------------
# Deployment Template for API-Service
# -----------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

# Deployment Spec
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    
    # POD Spec
    spec:

      # Service Account Details for the POD
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}

      # Use the docker-registry secret
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      # Container configuration for the POD
      containers:
        - name: csb-api-service
          image: {{ .Values.deployment.image.uri }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.liveness.timeoutSeconds }}
          
          # Readiness Probe 
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.readiness.timeoutSeconds }}
          
          # Resource configuration and limits for the POD
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}

          # Map non-sensitive environment variables from configmap
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config

          # Map sensitive environment variables from secret
          env:
            - name: API_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.apiToken.name }}
                  key: {{ .Values.secrets.apiToken.key }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgres.name }}
                  key: {{ .Values.secrets.postgres.key }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.redis.name }}
                  key: {{ .Values.secrets.redis.key }}