# -------------------------------
# Secrets Template for Helm Chart
# -------------------------------

{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.fullname" . }}-secret
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_AUTH_TOKEN: {{ .Values.secrets.apiAuthToken }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
{{- end -}}
