{{- if .Values.secrets.enabled -}}
# ----------------------------------------------------------------------
# Secrets Template for API-Service
#
# Note: This is only a placeholder to document the required secrets for app.
#       Actual secrets should be created via github pipeline.
# ----------------------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  API_AUTH_TOKEN: {{ .Values.secrets.apiAuthToken }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword }}
{{- end -}}
