# .github/actions/helm-deploy/action.yaml
# Install Helm chart for the API-Service.

name: "Helm Deploy"
description: "Deploys an application using Helm with dynamic values."

# *** ACTION INPUTS ***
# Defines the parameters this action accepts.
inputs:
  release_name:
    description: "The name for the Helm release (e.g., api-service-dev)."
    required: true
  namespace:
    description: "The target Kubernetes namespace."
    required: true
  chart_path:
    description: "The path to the Helm chart directory."
    required: true
  image_full_name:
    description: "The full Docker image name with tag to deploy."
    required: true
  values_overrides:
    description: "A string of additional --set arguments for the Helm command."
    required: false
    default: ""

# *** ACTION STEPS ***
# Defines the steps the action will run.
runs:
  using: "composite"
  steps:
    - name: Deploy with Helm
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.release_name }} ${{ inputs.chart_path }} \
          --namespace ${{ inputs.namespace }} \
          --set deployment.image.name='${{ inputs.image_full_name }}' \
          ${{ inputs.values_overrides }} \
          --wait
