/* ----------------------------------------------------------------------------
* CSecBridge Backend Schema Objects
*
* PURPOSE:
* This script defines and creates the core data model for the CSecBridge API
* service. It is designed to be idempotent, meaning it can be run multiple
* times without causing errors or unintended side effects.
*
* It performs the following actions:
* 1. Creates a custom 'status_enum' type for request states.
* 2. Creates the primary tables: 'csb_requests', 'csb_requests_audit', and 'csb_requests_ref'.
* 3. Adds descriptive comments (metadata) to tables and columns.
* 4. Creates performance-enhancing indexes on key columns.
* 5. Grants specific, least-privilege permissions to the service roles.
* 6. Implements Row-Level Security (RLS) policies to enforce data isolation
*    between different service roles (e.g., AWS vs. Azure workers).
*
* NOTE: All objects are created within the 'csb_app' schema, which is assumed
*       to have been created by the infrastructure provisioning automation.
*/ ----------------------------------------------------------------------------

-- Create a custom ENUM type for request status idempotently.
do $$
begin
    if not exists (select 1 from pg_type where typname = 'status_enum') then
        create type status_enum as enum (
            'success',
            'failed',
            'rollback',
            'queued',
            'in_progress'
        );
    end if;
end$$;

-- Create the primary table for tracking request state.
-- This table holds the current status and details of each request.
create table if not exists csb_app.csb_requests (
    correlation_id uuid primary key,
    client_req_id varchar(255) not null,
    status status_enum not null,
    req_time_stamp timestamptz not null default now(),
    last_upd_time_stamp timestamptz,
    cloud_provider varchar(50) not null,
    principal varchar(255),
    action varchar(50) not null,
    entitlement varchar(255) not null,
    account_id varchar(255)
);

-- Create the audit table for logging all state transitions.
-- This is an append-only log for historical tracking.
create table if not exists csb_app.csb_requests_audit (
    audit_id bigserial primary key,
    correlation_id uuid not null references csb_requests(correlation_id) on delete cascade,
    status status_enum not null,
    audit_timestamp timestamptz not null default now(),
    audit_log text
);

-- Create a reference table to link internal correlation IDs with external IDs
-- generated by cloud providers (e.g., a job ID from an AWS service).
create table if not exists csb_app.csb_requests_ref (
    ref_serial_id bigserial primary key,
    cloud_provider varchar(50) not null,
    correlation_id uuid not null references csb_requests(correlation_id) on delete cascade,
    ref_id varchar(255) not null,
    ref_upd_time_stamp timestamptz not null default now()
);

-- Set table and column metadata for clarity and documentation.
comment on column csb_requests.correlation_id is 'Unique id generated by the api service for internal tracking.';
comment on column csb_requests.status is 'The current status of the request (e.g., pending, success, failed).';
comment on table csb_requests is 'Primary table for maintaining state of each request.';
comment on table csb_requests_audit is 'An append-only log of all status changes for each request.';
comment on table csb_requests_ref is 'A log of all external Ids generated by the target provider.';

-- Create indexes to optimize query performance.
create index if not exists csb_requests_client_request_id_idx on csb_app.csb_requests(client_req_id); -- For looking up requests by the client's ID.
create index if not exists csb_requests_status_idx on csb_app.csb_requests(status); -- For efficiently finding all requests in a specific state (e.g., 'queued').
create index if not exists csb_requests_principal_idx on csb_app.csb_requests(principal); -- For querying requests by the initiating user/principal.
create index if not exists csb_requests_audit_correlation_id_idx on csb_app.csb_requests_audit(correlation_id); -- To quickly retrieve the audit history for a specific request.
create index if not exists csb_requests_ref_id_idx on csb_app.csb_requests_ref(cloud_provider, ref_id); -- For finding internal requests based on an external provider's ID.

--------------
-- PERMISSIONS
--------------

-- Grant permissions for the primary API service role 'csb_api_user'.
-- This role can create new requests and view/update their state.
grant select, insert, update on table csb_app.csb_requests to csb_api_user;
grant select, insert on table csb_app.csb_requests_audit to csb_api_user;
grant usage, select on sequence csb_app.csb_requests_audit_audit_id_seq to csb_api_user; -- Required for inserting into a table with a bigserial key.

-- Grant permissions for the 'csb_aws_user' worker role.
-- This role can view/update requests and insert audit/reference records.
grant select, update on table csb_app.csb_requests to csb_aws_user;
grant select, insert on table csb_app.csb_requests_audit to csb_aws_user;
grant select, insert on table csb_app.csb_requests_ref to csb_aws_user;
grant usage, select on sequence csb_app.csb_requests_audit_audit_id_seq to csb_aws_user;
grant usage, select on sequence csb_app.csb_requests_ref_ref_serial_id_seq to csb_aws_user;

-- Grant permissions for the 'csb_azure_user' worker role.
-- This role has the same permission set as the AWS worker.
grant select, update on table csb_app.csb_requests to csb_azure_user;
grant select, insert on table csb_app.csb_requests_audit to csb_azure_user;
grant select, insert on table csb_app.csb_requests_ref to csb_azure_user;
grant usage, select on sequence csb_app.csb_requests_audit_audit_id_seq to csb_azure_user;
grant usage, select on sequence csb_app.csb_requests_ref_ref_serial_id_seq to csb_azure_user;

---------------------------
-- ROW-LEVEL SECURITY (RLS)
---------------------------

alter table csb_app.csb_requests enable row level security;

-- Clean up old policies before creating new ones to ensure idempotency.
drop policy if exists csb_api_user_insert_policy on csb_app.csb_requests;
drop policy if exists csb_api_user_select_policy on csb_app.csb_requests;
drop policy if exists csb_aws_worker_policy on csb_app.csb_requests;
drop policy if exists csb_azure_worker_policy on csb_app.csb_requests;

-- The 'csb_api_user' can insert and select any row.
create policy csb_api_user_insert_policy on csb_app.csb_requests for insert to csb_api_user with check (true);
create policy csb_api_user_select_policy on csb_app.csb_requests for select to csb_api_user using (true);

-- Worker policies: These roles can only see and modify rows where the 'cloud_provider' column matches their designated provider.
create policy csb_aws_worker_policy on csb_app.csb_requests for all to csb_aws_user using (cloud_provider = 'aws') with check (cloud_provider = 'aws');
create policy csb_azure_worker_policy on csb_app.csb_requests for all to csb_azure_user using (cloud_provider = 'azure') with check (cloud_provider = 'azure');