# This Kustomize overlay configures the 'prod' environment.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base and add overlay-specific resources in a single list.
resources:
  - ../../base
  - role-binding.yaml

# Set the namespace for all resources in this overlay.
namespace: csecbridge-prod

# Apply patches to the base resources.
patches:
  - target:
      kind: Namespace
      name: csecbridge-placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: csecbridge-prod
      - op: replace
        path: /metadata/labels/name
        value: csecbridge-prod
