# ----------------------------------------
# Role binding template for prod Kustomize
# ----------------------------------------

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-deployer-role-binding
  namespace: csb-prod
subjects:
  - kind: ServiceAccount
    name: csb-app-sa
    namespace: csb-prod
roleRef:
  kind: Role
  name: csb-app-deployer-role
  apiGroup: rbac.authorization.k8s.io
