# Deployment Manager Role for CI.CD pipeline
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager-role
  # The namespace will be set automatically by the Kustomize overlay.
rules:
  # Core Kubernetes resources permissions
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      - deployments
      - services
      - pods
      - configmaps
      - secrets
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Autoscaling resources
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Read-only permissions for logs
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
