{{- if .Values.networkPolicy.enabled -}}
# ------------------------------------------------------------------------
# Network Policy for the Redis - allows incoming requests from API-Service
# ------------------------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  
  policyTypes:
  - Ingress

  ingress:
  # From API-Service Pod
  - from:
    - podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicy.ingress.fromApiService.podSelector | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end -}}
