{{- if .Values.secrets.create -}}
# ---------------------------------
# Secret Template for Redis Service
# ---------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  # The key name is 'password' which is mounted into the container as REDIS_PASSWORD
  {{ .Values.secret.key }}: {{ .Values.secret.value | quote }}
{{- end -}}
