# Default values for the api-service Helm chart.
# This file is structured to group values by the Kubernetes resource they
# primarily configure.

# *** DEPLOYMENTS ***
# Values that configure the api-service Deployment resource.
deployment:
  replicaCount: 1
  image:
    repository: csecbridge-api-service
    pullPolicy: IfNotPresent
    # The image tag. If not set, it defaults to the chart's appVersion.
    tag: ""
  # Resource requests and limits for the container.
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

# *** SERVICE ***
# Values for the Kubernetes Service that exposes the application internally.
service:
  type: ClusterIP
  # The port the service exposes.
  # NOTE: This value is also used by the Deployment's containerPort and probes.
  port: 8000

# *** INGRESS ***
# Values for the Ingress resource, which exposes the service externally.
ingress:
  enabled: false
  # Default hosts configuration.
  hosts:
    - host: csecbridge-api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # Default annotations for an NGINX Ingress controller.
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

# *** AUTO SCALING ***
# Configuration for the HorizontalPodAutoscaler (HPA).
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# *** CONFIG MAP ***
# Non-sensitive configuration passed to the application as environment variables.
config:
  cacheTtlSeconds: 300
  postgresMaxConn: 5
  allowedOrigin: "http://localhost:3000"
  # Connection details for backend services
  postgresHost: "postgres-service"
  postgresPort: 5432
  postgresUser: "csecbridge_user"
  postgresDb: "csecbridge_db"
  redisHost: "redis-service"
  redisPort: 6379
  # SSL/TLS settings
  postgresSslEnabled: false
  redisSslEnabled: false

# *** SECRETS ***
# Configuration for sensitive data.
secrets:
  # This is only a placeholder for documentational purpose.
  # Secrets will be created via CI-CD pipeline, prior to installing helm
  create: false
  apiAuthToken: ""
  postgresPassword: ""
  redisPassword: ""

# *** NETWORK POLICY ***
# Configures the NetworkPolicy resource to firewall the application pods.
networkPolicy:
  enabled: true

  # Egress rules define the outbound connections allowed FROM the api-service.
  egress:
    # Selector for the PostgreSQL pods.
    postgres:
      podSelector:
        app.kubernetes.io/name: postgresql
    # Selector for the Redis pods.
    redis:
      podSelector:
        app.kubernetes.io/name: redis
    # Selector for the Kubernetes DNS service (CoreDNS).
    dns:
      podSelector:
        k8s-app: kube-dns
