/* ----------------------------------------------------------------------------
* Create backend objects for API-Service.
*
* 1. REQUESTS - Main table for maintaining the current state of a request.
* 2. REQUESTS_AUDIT - Audit table for logging all the events.
* 3. Set owner for the tables
* 4. Set meta data for tables and columns
* 5. Create Indices for the tables.
* 6. Set permissions for API User on the tables for absolute necessary actions.
*
* NOTE: Objects will be created using the application schema - CSB_APP
* 
*/ ----------------------------------------------------------------------------

CREATE TABLE CSB_REQUESTS (
    CORRELATION_ID UUID PRIMARY KEY,
    CLIENT_REQ_ID VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    REQ_TIME_STAMP TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    LAST_UPD_TIME_STAMP TIMESTAMPTZ,
    CLOUD_PROVIDER VARCHAR(50) NOT NULL,
    PRINCIPAL VARCHAR(255) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    ACCOUNT_ID VARCHAR(255)
);

CREATE TABLE CSB_REQUESTS_AUDIT (
    AUDIT_ID BIGSERIAL PRIMARY KEY,
    CORRELATION_ID UUID NOT NULL REFERENCES REQUESTS(CORRELATION_ID) ON DELETE CASCADE,
    STATUS VARCHAR(50) NOT NULL,
    AUDIT_TIMESTAMP TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ERROR_TEXT TEXT
);

-- Set the column meta data
COMMENT ON COLUMN CSB_REQUESTS.CORRELATION_ID IS 'Unique ID generated by the API service for internal tracking.';
COMMENT ON COLUMN CSB_REQUESTS.STATUS IS 'The current status of the request (e.g., PENDING, SUCCESS, FAILED).';
COMMENT ON TABLE CSB_REQUESTS_AUDIT IS 'An append-only log of all status changes for each request.';

-- Create indices
CREATE INDEX CSB_REQUESTS_CLIENT_REQUEST_ID_IDX ON CSB_REQUESTS(CLIENT_REQUEST_ID);
CREATE INDEX CSB_REQUESTS_STATUS_IDX ON CSB_REQUESTS(STATUS);
CREATE INDEX CSB_REQUESTS_PRINCIPAL_IDX ON CSB_REQUESTS(PRINCIPAL);
CREATE INDEX CSB_REQUESTS_AUDIT_CORRELATION_ID_IDX ON CSB_REQUESTS_AUDIT(CORRELATION_ID);

-- Grant permisions for service level user.
GRANT SELECT, INSERT, UPDATE ON TABLE REQUESTS TO CSB_API_USER;
GRANT SELECT, INSERT ON TABLE REQUESTS_AUDIT TO CSB_API_USER;

-- The audit_id is auto-generating, so the user needs usage permission on the sequence.
GRANT USAGE, SELECT ON SEQUENCE CSB_REQUESTS_AUDIT_AUDIT_ID_SEQ TO CSB_API_USER;

-- Explicitly REVOKE all other permissions to enforce least privilege.
REVOKE TRUNCATE, DELETE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA PUBLIC FROM CSB_API_USER;